import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import TanstackProvider from "../../provider/TanstackProvider";
import AuthProvider from "../../provider/auth.provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "LiveWithCodeAnkit",
  description: "Generated by LiveWithCodeAnkit",
  openGraph: {
    title: "LiveWithCodeAnkit",
    description: "Generated by LiveWithCodeAnkit",
    url: "https://github.com/LiveWithCodeAnkit",
    siteName: "LiveWithCodeAnkit",
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <TanstackProvider>
            {children}
            <ToastContainer />
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
